# This message contains dynamic info about a vehicle wheel

float32 steer_angle     # rotation angle (in degrees) of the wheel about the "up" vector
float32 pitch_angle     # rotation angle (in degrees) about the rolling axis for the wheel
float32 height          # Height (in meters) of the wheel. Comes from Suspension Offset.
float32 speed           # Rotation speed (in degrees per second) about the rolling axis of the wheel.
float32 lat_slip_angle  # lateral slip angle (in degrees) experienced by the wheel
float32 long_slip_ratio # longitudinal slip ratio experienced by the wheel
